apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # How frequently Prometheus will scrape targets

    scrape_configs:
      - job_name: 'kubernetes'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [flask-app,mongo]
            action: keep
            regex: flask

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager-service:9093  # Alertmanager service name and port

    rule_files:
      - "/etc/prometheus/alert-rules.yml"  # Load alerting rules from this file
