prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  config:
    global:
      slack_api_url: url: "https://hooks.slack.com/services/YOUR_WORKSPACE/YOUR_CHANNEL/SECRET_TOKEN"
  alertmanagerSpec:
    alertmanagerConfigNamespaceSelector:
    alertmanagerConfigSelector:
    alertmanagerConfigMatcherStrategy:
      type: None