apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-replication-controller
spec:
  replicas: 1  # Specify the desired number of replicas
  selector:
    app: flask  # Label selector to match pods
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-app
        image: navdeepmk/navdeepmk_docker_test  # Replace with your Docker image
        ports:
          - containerPort: 5000
        env:
          - name: MONGO_HOST
            value: mongodb-service.default.svc.cluster.local
          - name: MONGO_PORT
            value: "27017"
          - name: FLASK_ENV
            value: "production"              